{
 "title": "Netology",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Load average 5m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(avg by (instance)(node_load5{group=\"nginx\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization in %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance)(irate(node_cpu_seconds_total{group=\"nginx\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free memory in %",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "100 * ((avg_over_time(node_memory_MemFree_bytes{group=\"nginx\"}[1m]) + avg_over_time(node_memory_Cached_bytes{group=\"nginx\"}[1m]) + avg_over_time(node_memory_Buffers_bytes{group=\"nginx\"}[1m])) / avg_over_time(node_memory_MemTotal_bytes{group=\"nginx\"}[1m]))"
    }
   ]
  },
  {
   "title": "Memory uzilization on nginx-1",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"192.168.11.32:9100\"} / (node_memory_MemTotal_bytes{instance=\"192.168.11.32:9100\"})))* 100"
    }
   ]
  },
  {
   "title": "Memory utilization on Nginx-2",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 9, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"192.168.12.18:9100\"} / (node_memory_MemTotal_bytes{instance=\"192.168.12.18:9100\"})))* 100"
    }
   ]
  },
  {
   "title": "Disk write Kb/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{instance=~'192.168.11.32:9100|192.168.12.18:9100', device=\"vda\"}[1m]) / 1024"
    }
   ]
  },
  {
   "title": "Disk read kb/s",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 13 },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=~'192.168.11.32:9100|192.168.12.18:9100', device=\"vda\"}[1m]) / 1024"
    }
   ]
  },
  {
   "title": "Disk usage on Nginx-1",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=~'192.168.11.32:9100',mountpoint=~\"/\"}-node_filesystem_free_bytes{instance=~'192.168.11.32:9100',mountpoint=~\"/\"}) *100/(node_filesystem_avail_bytes {instance=~'192.168.11.32:9100',mountpoint=~\"/\"}+(node_filesystem_size_bytes{instance=~'192.168.11.32:9100',mountpoint=~\"/\"}-node_filesystem_free_bytes{instance=~'192.168.11.32:9100',mountpoint=~\"/\"}))"
    }
   ]
  },
  {
   "title": "Disk usage on Nginx-2",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=~'192.168.12.18:9100',mountpoint=~\"/\"}-node_filesystem_free_bytes{instance=~'192.168.12.18:9100',mountpoint=~\"/\"}) *100/(node_filesystem_avail_bytes {instance=~'192.168.12.18:9100',mountpoint=~\"/\"}+(node_filesystem_size_bytes{instance=~'192.168.12.18:9100',mountpoint=~\"/\"}-node_filesystem_free_bytes{instance=~'192.168.12.18:9100',mountpoint=~\"/\"}))"
    }
   ]
  },
  {
   "title": "Network utilization - in",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{group=~'nginx',device=~\"eth0\"}[1m]) * 8 / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Network utilization - out",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{group=~'nginx',device=~\"eth0\"}[1m]) * 8 / 1024 / 1024"
    }
   ]
  },
  {
   "title": "http_response_size_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "nginx_http_response_size_bytes{group=\"nginx-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http_response_count_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 26 },
   "targets": [
    {
     "expr": "nginx_http_response_count_total{group=\"nginx-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}